/*
 * JS for Map generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return '6b6ca046-473c-4601-9541-fc02f086f347';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

// Deprecated


function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "startScreen",
    "location": "startScreen.html"
}, {
    "name": "Map",
    "location": "Map.html"
}, {
    "name": "panel",
    "location": "panel.html"
}];

Map_js = function(runBeforeShow) {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'googlemap_2': 'Map_googlemap_2',
        'marker_3': 'Map_marker_3'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    if (navigator.userAgent.indexOf("IEMobile") != -1) {
        //Fix for jQuery Mobile's footer in Cordova webview on WP8 devices
        var msViewportStyle = document.createElement("style");
        msViewportStyle.appendChild(
        document.createTextNode("@media screen and (orientation: portrait){@-ms-viewport {width: 320px; height: 534px;user-zoom: fixed;zoom: 1;}}" + "@media screen and (orientation:landscape){@-ms-viewport{width:480px;user-zoom:fixed;zoom:1;}}"));
        document.getElementsByTagName("head")[0].appendChild(msViewportStyle);
    }

    Apperyio.CurrentScreen = 'Map';

    /*
     * Nonvisual components
     */
    var datasources = [];

    mobilecamera1 = new Apperyio.DataSource(CameraService, {
        'onBeforeSend': function(jqXHR) {

        },
        'onComplete': function(jqXHR, textStatus) {

            Apperyio.refreshScreenFormElements("Map");
        },
        'onSuccess': function(data) {},
        'onError': function(jqXHR, textStatus, errorThrown) {},
        'responseMapping': [],
        'requestMapping': [{
            'PATH': ['quality'],
            'TYPE': 'STRING',
            'ATTR': '80'
        }, {
            'PATH': ['destinationType'],
            'TYPE': 'STRING',
            'ATTR': 'Data URL'
        }, {
            'PATH': ['sourcetype'],
            'TYPE': 'STRING',
            'ATTR': 'Camera'
        }, {
            'PATH': ['allowedit'],
            'TYPE': 'STRING',
            'ATTR': 'true'
        }, {
            'PATH': ['encodingType'],
            'TYPE': 'STRING',
            'ATTR': 'JPEG'
        }, {
            'PATH': ['targetWidth'],
            'TYPE': 'STRING',
            'ATTR': '1024'
        }, {
            'PATH': ['targetHeight'],
            'TYPE': 'STRING',
            'ATTR': '768'
        }]
    });

    datasources.push(mobilecamera1);

    /*
     * Events and handlers
     */

    // Before Show
    var Map_beforeshow = function() {
            Apperyio.CurrentScreen = "Map";
            for (var idx = 0; idx < datasources.length; idx++) {
                datasources[idx].__setupDisplay();
            }
        };

    // On Load
    var Map_onLoad = function() {
            Map_elementsExtraJS();

            try {
                mobilecamera1.execute({})
            } catch (ex) {
                console.log(ex.name + '  ' + ex.message);
                hideSpinner();
            };

            // TODO fire device events only if necessary (with JS logic)
            Map_deviceEvents();
            Map_windowEvents();
            Map_elementsEvents();
        };

    // screen window events
    var Map_windowEvents = function() {

            $('#Map').bind('pageshow orientationchange', function() {
                var _page = this;
                adjustContentHeightWithPadding(_page);
            });

        };

    // device events
    var Map_deviceEvents = function() {
            document.addEventListener("deviceready", function() {

            });
        };

    // screen elements extra js
    var Map_elementsExtraJS = function() {
            // screen (Map) extra code

            /* googlemap_2 */

            $("[name = 'googlemap_2']").wrap("<div/>");
            $("[name = 'googlemap_2']").parent().css("margin-left", $("[name = 'googlemap_2']").css("margin-left"));
            $("[name = 'googlemap_2']").parent().css("margin-right", $("[name = 'googlemap_2']").css("margin-right"));
            $("[name = 'googlemap_2']").css("margin-left", '0');
            $("[name = 'googlemap_2']").css("margin-right", '0');

            var googlemap_2_options = {
                markerSourceName: "googlemap_2_markers",
                latitude: "",
                longitude: "",
                address: "San Francisco, CA",
                zoom: 10,
                showLocationMarker: false
            }

            Apperyio.__registerComponent('googlemap_2', new Apperyio.ApperyMapComponent("googlemap_2", googlemap_2_options));
            $("[name='googlemap_2_markers'] [apperytype='marker']").attr("reRender", "googlemap_2");
            $("[name='googlemap_2']").closest("[data-role='page']").bind({
                pagecontainershow: function() {
                    if (Apperyio('googlemap_2') != undefined) {
                        Apperyio('googlemap_2').refresh();
                    }
                }
            });

        };

    // screen elements handler
    var Map_elementsEvents = function() {
            $(document).on("click", "a :input,a a,a fieldset label", function(event) {
                event.stopPropagation();
            });

        };

    $(document).off("pagebeforeshow", "#Map").on("pagebeforeshow", "#Map", function(event, ui) {
        Map_beforeshow();
    });

    if (runBeforeShow) {
        Map_beforeshow();
    } else {
        Map_onLoad();
    }
};

$(document).off("pagecreate", "#Map").on("pagecreate", "#Map", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    Map_js();
});