/*
 * JS for panel generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return '6b6ca046-473c-4601-9541-fc02f086f347';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

// Deprecated


function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "startScreen",
    "location": "startScreen.html"
}, {
    "name": "panel",
    "location": "panel.html"
}];

panel_js = function(runBeforeShow) {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilenavbar_2': 'panel_mobilenavbar_2',
        'mobilenavbaritem_3': 'panel_mobilenavbaritem_3',
        'mobilenavbaritem_4': 'panel_mobilenavbaritem_4',
        'mobilenavbaritem_5': 'panel_mobilenavbaritem_5'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    if (navigator.userAgent.indexOf("IEMobile") != -1) {
        //Fix for jQuery Mobile's footer in Cordova webview on WP8 devices
        var msViewportStyle = document.createElement("style");
        msViewportStyle.appendChild(
        document.createTextNode("@media screen and (orientation: portrait){@-ms-viewport {width: 320px; height: 534px;user-zoom: fixed;zoom: 1;}}" + "@media screen and (orientation:landscape){@-ms-viewport{width:480px;user-zoom:fixed;zoom:1;}}"));
        document.getElementsByTagName("head")[0].appendChild(msViewportStyle);
    }

    Apperyio.CurrentScreen = 'panel';

    /*
     * Nonvisual components
     */
    var datasources = [];

    mobilecamera1 = new Apperyio.DataSource(CameraService, {
        'onBeforeSend': function(jqXHR) {

        },
        'onComplete': function(jqXHR, textStatus) {

            Apperyio.refreshScreenFormElements("panel");
        },
        'onSuccess': function(data) {},
        'onError': function(jqXHR, textStatus, errorThrown) {},
        'responseMapping': [],
        'requestMapping': [{
            'PATH': ['quality'],
            'TYPE': 'STRING',
            'ATTR': '80'
        }, {
            'PATH': ['destinationType'],
            'TYPE': 'STRING',
            'ATTR': 'Data URL'
        }, {
            'PATH': ['sourcetype'],
            'TYPE': 'STRING',
            'ATTR': 'Camera'
        }, {
            'PATH': ['allowedit'],
            'TYPE': 'STRING',
            'ATTR': 'true'
        }, {
            'PATH': ['encodingType'],
            'TYPE': 'STRING',
            'ATTR': 'JPEG'
        }, {
            'PATH': ['targetWidth'],
            'TYPE': 'STRING',
            'ATTR': '1024'
        }, {
            'PATH': ['targetHeight'],
            'TYPE': 'STRING',
            'ATTR': '768'
        }]
    });

    datasources.push(mobilecamera1);

    /*
     * Events and handlers
     */

    // Before Show
    var panel_beforeshow = function() {
            Apperyio.CurrentScreen = "panel";
            for (var idx = 0; idx < datasources.length; idx++) {
                datasources[idx].__setupDisplay();
            }
        };

    // On Load
    var panel_onLoad = function() {
            panel_elementsExtraJS();

            // TODO fire device events only if necessary (with JS logic)
            panel_deviceEvents();
            panel_windowEvents();
            panel_elementsEvents();
        };

    // screen window events
    var panel_windowEvents = function() {

            $('#panel').bind('pageshow orientationchange', function() {
                var _page = this;
                adjustContentHeightWithPadding(_page);
            });

        };

    // device events
    var panel_deviceEvents = function() {
            document.addEventListener("deviceready", function() {

            });
        };

    // screen elements extra js
    var panel_elementsExtraJS = function() {
            // screen (panel) extra code

        };

    // screen elements handler
    var panel_elementsEvents = function() {
            $(document).on("click", "a :input,a a,a fieldset label", function(event) {
                event.stopPropagation();
            });

            $(document).off("click", '#panel_mobileheader [name="mobilenavbaritem_4"]').on({
                click: function() {
                    if (!$(this).attr('disabled')) {
                        try {
                            mobilecamera1.execute({})
                        } catch (ex) {
                            console.log(ex.name + '  ' + ex.message);
                            hideSpinner();
                        };

                    }
                },
            }, '#panel_mobileheader [name="mobilenavbaritem_4"]');

        };

    $(document).off("pagebeforeshow", "#panel").on("pagebeforeshow", "#panel", function(event, ui) {
        panel_beforeshow();
    });

    if (runBeforeShow) {
        panel_beforeshow();
    } else {
        panel_onLoad();
    }
};

$(document).off("pagecreate", "#panel").on("pagecreate", "#panel", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    panel_js();
});